%% Author: Gil Serrancolí
% Note that the paths need to be adapted according to your folders.

NVIDIA_dir='D:\ProgramFiles_HDD\NVIDIA GPU Computing Toolkit\';

mex(['-I',NVIDIA_dir,'CUDA\v10.1\cuda\include'],...
    ['-I',NVIDIA_dir,'CUDA\v10.1\cuda\lib\x64'],...
    ['-I','D:\Gil\OpenPose\3rdparty\windows\caffe3rdparty\include\'],...
    ['-I','D:\Gil\OpenPose\3rdparty\windows\opencv\include\'],...
    ['-I','D:\Gil\OpenPose\include\'],...
    ['-I','D:\Gil\OpenPose\include\openpose'],...
    ['-L','D:\Gil\OpenPose\3rdparty\windows\caffe_cpu\include'],...    
    ['-L','D:\Gil\OpenPose\3rdparty\windows\caffe_cpu\include2'],... %['-L','D:\Gil\OpenPose\3rdparty\windows\caffe3rdparty\lib\'],...
    ['-L','D:\Gil\OpenPose\3rdparty\windows\caffe3rdparty\include'],...
    ['-L','D:\Gil\OpenPose\3rdparty\eigen\include'],...
    ['-L','D:\Gil\OpenPose\3rdparty\windows\caffe3rdparty\lib\'],...
    ['-l','gflags.lib'],...
    ['-L','D:\Gil\OpenPose\3rdparty\windows\opencv\x64\vc15\lib\'],...
    ['-l','opencv_world401.lib'],...
    ['-L','D:\Gil\OpenPose\build\x64\Release\'],...
    ['-L','D:\Gil\OpenPose\build\src\openpose\Release\'],...
    ['-l','OpenPose.lib'],...
    ['-I','C:\Program Files (x86)\Windows Kits\10\bin\x86'],... %%['-I','C:\Program Files (x86)\Windows Kits\8.1\bin\x86'],...
    ['-I','C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools'],...
    ['-I','C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt'],...  %['-I','C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt'],...
    ['-I','C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um'],... %['-I','C:\Program Files (x86)\Windows Kits\8.1\Include\um'],...
    ['-I','C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared'],...  %['-I','C:\Program Files (x86)\Windows Kits\8.1\Include\shared'],...   
    ['-I','C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt'],...   %['-I','C:\Program Files (x86)\Windows Kits\8.1\Include\winrt'],...
    ['-L','C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64'],...    %['-L','C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64'],...
    ['-I','D:\ProgramFiles_HDD\Microsoft Visual Studio 14.0\VC\lib\amd64'],....
    ['-I','D:\ProgramFiles_HDD\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64'],...
            'Process_Image_MEX.cpp')

